[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = "enigma-machine"
version = "0.1.0"
description = "Package for encrypting messages using enigma encryption from WW2"
readme = "README.md"
requires-python = ">=3.14"
license = "MIT"
authors = [
    { name = "Petter Gustafsson", email = "petter.gustafsson1998@gmail.com" }
]

dependencies = [

]

[tool.poetry]
packages = [
    {include = "enigma_machine", from = "src"}
]

[dependency-groups]
dev = [
    "pytest>=9.1.1",
    "ruff>=0.15.21",
    "mypy>=2.2.0",
]

[tool.ruff]
line-length = 120

[tool.ruff.lint]
select = [
    "E",    # pycodestyle errors
    "W",    # pycodestyle warnings
    "F",    # Pyflakes
    "I",    # isort (import sorting)
    "UP",   # pyupgrade
    "B",    # flake8-bugbear
    "SIM",  # flake8-simplify
    "C4",   # flake8-comprehensions
    "RUF",  # Ruff-specific rules
    "ANN",  # type annotations
    "D",    # pydocstyle
]

ignore = [
    "D203", # incompatible with D211
    "D213", # use D212 instead
]

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
line-ending = "lf"

[tool.mypy]
python_version = "3.14"

strict = true

warn_return_any = true
warn_unused_configs = true
warn_redundant_casts = true
warn_unused_ignores = true
warn_unreachable = true
warn_no_return = true

show_error_codes = true
pretty = true